export type Career = {
  id: string;
  name: string;
  nameRu: string;
  class: string;
  classRu: string;
  status: string;
  level: "_ENTRY" | "INTERMEDIATE" | "ADVANCED" | "EXPERT";
  skills: string[];
  talents: string[];
  characteristics: Record<string, number>;
};

export const CAREERS: Career[] = [
  {
    id: "agitator",
    name: "Agitator",
    nameRu: "Агитатор",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["charm", "leadership", "common-knowledge-reikkland", "bribery"],
    talents: ["charm", "blather"],
    characteristics: { fel: 10 },
  },
  {
    id: "apprentice-wizard",
    name: "Apprentice Wizard",
    nameRu: "Ученик мага",
    class: "Academics",
    classRu: "Академик",
    status: "None",
    level: "_ENTRY",
    skills: [
      "language-additional",
      "magical-awareness",
      "perception",
      "language-wester",
    ],
    talents: ["petty-magic", "arcane-magic"],
    characteristics: { int: 10 },
  },
  {
    id: "barracks-guard",
    name: "Barracks Guard",
    nameRu: "Казарменный стражник",
    class: "Military",
    classRu: "Военный",
    status: "None",
    level: "_ENTRY",
    skills: ["perception", "intimidate", "dodge", "common-knowledge-reikkland"],
    talents: ["stance", "strike-mighty"],
    characteristics: { ws: 10 },
  },
  {
    id: "boatman",
    name: "Boatman",
    nameRu: "Лодочник",
    class: "Riverfolk",
    classRu: "Речной народ",
    status: "None",
    level: "_ENTRY",
    skills: ["row", "sail", "perception", "common-knowledge-reikkland"],
    talents: ["river-child", "orientation"],
    characteristics: { ag: 10 },
  },
  {
    id: "bounty-hunter",
    name: "Bounty Hunter",
    nameRu: "Охотник за головами",
    class: "Rangers",
    classRu: "Следопыт",
    status: "None",
    level: "_ENTRY",
    skills: ["track", "search", "perception", "intimidate"],
    talents: ["nose-for-business", "hunter"],
    characteristics: { i: 10 },
  },
  {
    id: "bravo",
    name: "Bravo",
    nameRu: "Браво",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["dodge", "intimidate", "street-fighting", "brawling"],
    talents: ["menacing", "quick-draw"],
    characteristics: { s: 10 },
  },
  {
    id: "burghers-guard",
    name: "Burgher's Guard",
    nameRu: "Стража горожанина",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["perception", "dodge", "common-knowledge-reikkland", "leadership"],
    talents: ["watchman", "sturdy"],
    characteristics: { t: 10 },
  },
  {
    id: "camp-follower",
    name: "Camp Follower",
    nameRu: "Обозник",
    class: "Military",
    classRu: "Военный",
    status: "None",
    level: "_ENTRY",
    skills: [
      "animal-care",
      "endurance",
      "set-traps",
      "common-knowledge-reikkland",
    ],
    talents: ["carouser", "hardy"],
    characteristics: { wp: 10 },
  },
  {
    id: "charmer",
    name: "Charmer",
    nameRu: "Искуситель",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["charm", "beauty", "gossip", "perform"],
    talents: ["suave", "attractive"],
    characteristics: { fel: 10 },
  },
  {
    id: "coachman",
    name: "Coachman",
    nameRu: "Кучер",
    class: "Riverfolk",
    classRu: "Речной народ",
    status: "None",
    level: "_ENTRY",
    skills: [
      "drive-cart",
      "ride-horse",
      "animal-care",
      "common-knowledge-reikkland",
    ],
    talents: ["trick-riding", "speed-reader"],
    characteristics: { ag: 10 },
  },
  {
    id: "entertainer",
    name: "Entertainer",
    nameRu: "Артист",
    class: "Entertainers",
    classRu: "Артист",
    status: "None",
    level: "_ENTRY",
    skills: ["perform", "charm", "gossip", "entertain-singing"],
    talents: ["suave", "attractive"],
    characteristics: { fel: 10 },
  },
  {
    id: "farmer",
    name: "Farmer",
    nameRu: "Фермер",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: ["animal-care", "endurance", "outdoor-survival", "athletics"],
    talents: ["hardy", "seasoned-traveller"],
    characteristics: { t: 10 },
  },
  {
    id: "grave-robber",
    name: "Grave Robber",
    nameRu: "Могильщик",
    class: "Rangers",
    classRu: "Следопыт",
    status: "None",
    level: "_ENTRY",
    skills: ["athletics", "stealth", "search", "outdoor-survival"],
    talents: ["alley-cat", "second-sight"],
    characteristics: { ag: 10 },
  },
  {
    id: "herbalist",
    name: "Herbalist",
    nameRu: "Травник",
    class: "Academics",
    classRu: "Академик",
    status: "None",
    level: "_ENTRY",
    skills: ["heal", "trade-herbalist", "outdoor-survival", "identify-plant"],
    talents: ["herbalist", "tinker"],
    characteristics: { int: 10 },
  },
  {
    id: "hunter",
    name: "Hunter",
    nameRu: "Охотник",
    class: "Rangers",
    classRu: "Следопыт",
    status: "None",
    level: "_ENTRY",
    skills: ["trade-hunter", "outdoor-survival", "set-traps", "track"],
    talents: ["hunter", "trick-riding"],
    characteristics: { ag: 10 },
  },
  {
    id: "indulgent-aristocrat",
    name: "Indulgent Aristocrat",
    nameRu: "Аристократ",
    class: "Nobles",
    classRu: "Дворянин",
    status: "Gold 4",
    level: "_ENTRY",
    skills: ["charm", "leadership", "ride-horse", "trade-merchant"],
    talents: ["attractive", "scholar"],
    characteristics: { fel: 10 },
  },
  {
    id: "initiate",
    name: "Initiate",
    nameRu: "Послушник",
    class: "Academics",
    classRu: "Академик",
    status: "None",
    level: "_ENTRY",
    skills: ["pray", "heal", "literacy", "common-knowledge-reikkland"],
    talents: ["blather", "holy-minister"],
    characteristics: { wp: 10 },
  },
  {
    id: "jailer",
    name: "Jailer",
    nameRu: "Тюремщик",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["perception", "intimidate", "search", "climb"],
    talents: ["iron-jaw", "menacing"],
    characteristics: { s: 10 },
  },
  {
    id: "knot-warrior",
    name: "Knot Warrior",
    nameRu: "Узлователь",
    class: "Military",
    classRu: "Военный",
    status: "None",
    level: "_ENTRY",
    skills: ["brawling", "dodge", "intimidate", "grapple"],
    talents: ["iron-jaw", "wrestler"],
    characteristics: { s: 10 },
  },
  {
    id: "man-at-arms",
    name: "Man-at-Arms",
    nameRu: "Оруженосец",
    class: "Military",
    classRu: "Военный",
    status: "None",
    level: "_ENTRY",
    skills: ["melee-basic", "athletics", "dodge", "endurance"],
    talents: ["strike-mighty", "iron-jaw"],
    characteristics: { ws: 10 },
  },
  {
    id: "mason",
    name: "Mason",
    nameRu: "Каменщик",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: [
      "trade-mason",
      "climb",
      "perception",
      "common-knowledge-reikkland",
    ],
    talents: ["strong-mind", "craftsman"],
    characteristics: { s: 10 },
  },
  {
    id: "merchant",
    name: "Merchant",
    nameRu: "Купец",
    class: "Citizens",
    classRu: "Горожанин",
    status: "Silver 3",
    level: "_ENTRY",
    skills: [
      "trade-merchant",
      "gamble",
      "persuade",
      "common-knowledge-reikkland",
    ],
    talents: ["dealer", "shrewd"],
    characteristics: { fel: 10 },
  },
  {
    id: "messenger",
    name: "Messenger",
    nameRu: "Гонец",
    class: "Riverfolk",
    classRu: "Речной народ",
    status: "None",
    level: "_ENTRY",
    skills: ["ride-horse", "athletics", "endurance", "navigation"],
    talents: ["fleet-footed", "savanna-dweller"],
    characteristics: { ag: 10 },
  },
  {
    id: "miller",
    name: "Miller",
    nameRu: "Мельник",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: ["trade-miller", "animal-care", "athletics", "endurance"],
    talents: ["burly", "craftsman"],
    characteristics: { s: 10 },
  },
  {
    id: "miner",
    name: "Miner",
    nameRu: "Шахтёр",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: ["trade-miner", "endurance", "climb", "common-knowledge-dwarfs"],
    talents: ["burly", "tunnel-rat"],
    characteristics: { s: 10 },
  },
  {
    id: "noble-bastard",
    name: "Noble Bastard",
    nameRu: "Незаконнорождённый дворянин",
    class: "Nobles",
    classRu: "Дворянин",
    status: "Silver 2",
    level: "_ENTRY",
    skills: ["charm", "bribe", "gamble", "ride-horse"],
    talents: ["suave", "attractive"],
    characteristics: { fel: 10 },
  },
  {
    id: "outlaw",
    name: "Outlaw",
    nameRu: "Разбойник",
    class: "Rangers",
    classRu: "Следопыт",
    status: "None",
    level: "_ENTRY",
    skills: ["stealth", "outdoor-survival", "set-traps", "intimidate"],
    talents: ["dirty-fighting", "harbor"],
    characteristics: { ag: 10 },
  },
  {
    id: "peasant",
    name: "Peasant",
    nameRu: "Крестьянин",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: ["animal-care", "endurance", "outdoor-survival", "athletics"],
    talents: ["hardy", "strong-back"],
    characteristics: { t: 10 },
  },
  {
    id: "pit-fighter",
    name: "Pit Fighter",
    nameRu: "Боец ямы",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["brawling", "dodge", "intimidate", "endurance"],
    talents: ["iron-jaw", "dirty-fighting"],
    characteristics: { s: 10 },
  },
  {
    id: "porter",
    name: "Porter",
    nameRu: "Носильщик",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: ["endurance", "athletics", "swim", "climb"],
    talents: ["strong-back", "burly"],
    characteristics: { s: 10 },
  },
  {
    id: "priest",
    name: "Priest",
    nameRu: "Священник",
    class: "Academics",
    classRu: "Академик",
    status: "None",
    level: "_ENTRY",
    skills: ["pray", "heal", "charm", "common-knowledge-reikkland"],
    talents: ["devout", "scholar"],
    characteristics: { wp: 10 },
  },
  {
    id: "rat-catcher",
    name: "Rat Catcher",
    nameRu: "Истребитель крыс",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["set-traps", "trade-poison", "stealth", "outdoor-survival"],
    talents: ["rat-catcher", "poisoner"],
    characteristics: { ag: 10 },
  },
  {
    id: "recruit",
    name: "Recruit",
    nameRu: "Новобранец",
    class: "Military",
    classRu: "Военный",
    status: "None",
    level: "_ENTRY",
    skills: ["melee-basic", "athletics", "dodge", "endurance"],
    talents: ["teamwork", "drilled"],
    characteristics: { ws: 10 },
  },
  {
    id: "regimental-commander",
    name: "Regimental Commander",
    nameRu: "Командир полка",
    class: "Military",
    classRu: "Военный",
    status: "None",
    level: "_ENTRY",
    skills: [
      "leadership",
      "tactics",
      "ride-horse",
      "common-knowledge-reikkland",
    ],
    talents: ["inspiring", "veteran"],
    characteristics: { fel: 10 },
  },
  {
    id: "rhndr",
    name: "Rhire",
    nameRu: "Рейнджер",
    class: "Rangers",
    classRu: "Следопыт",
    status: "None",
    level: "_ENTRY",
    skills: ["stealth", "outdoor-survival", "track", "navigation"],
    talents: ["stalker", "tracker"],
    characteristics: { i: 10 },
  },
  {
    id: "scholar",
    name: "Scholar",
    nameRu: "Учёный",
    class: "Academics",
    classRu: "Академик",
    status: "None",
    level: "_ENTRY",
    skills: ["literacy", "research", "language-additional", "perception"],
    talents: ["scholar", "bookish"],
    characteristics: { int: 10 },
  },
  {
    id: "seaman",
    name: "Seaman",
    nameRu: "Моряк",
    class: "Riverfolk",
    classRu: "Речной народ",
    status: "None",
    level: "_ENTRY",
    skills: ["sail", "row", "swim", "climb"],
    talents: ["water-born", "strong-mind"],
    characteristics: { t: 10 },
  },
  {
    id: "servant",
    name: "Servant",
    nameRu: "Слуга",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["gossip", "dodge", "charm", "climb"],
    talents: ["subterfuge", "light-fingers"],
    characteristics: { ag: 10 },
  },
  {
    id: "shepherd",
    name: "Shepherd",
    nameRu: "Пастух",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: ["animal-care", "outdoor-survival", "charm-animal", "athletics"],
    talents: ["animal-affinity", "strong-back"],
    characteristics: { wp: 10 },
  },
  {
    id: "shield-bearer",
    name: "Shield Bearer",
    nameRu: "Щитоносец",
    class: "Military",
    classRu: "Военный",
    status: "None",
    level: "_ENTRY",
    skills: ["melee-basic", "dodge", "athletics", "endurance"],
    talents: ["defensive-fighting", "iron-jaw"],
    characteristics: { t: 10 },
  },
  {
    id: "squire",
    name: "Squire",
    nameRu: "Оруженосец",
    class: "Nobles",
    classRu: "Дворянин",
    status: "None",
    level: "_ENTRY",
    skills: ["melee-basic", "ride-horse", "tournament", "endurance"],
    talents: ["warrior-born", "squire"],
    characteristics: { ws: 10 },
  },
  {
    id: "student",
    name: "Student",
    nameRu: "Студент",
    class: "Academics",
    classRu: "Академик",
    status: "None",
    level: "_ENTRY",
    skills: ["literacy", "language-additional", "research", "gamble"],
    talents: ["scholar", "bookish"],
    characteristics: { int: 10 },
  },
  {
    id: "thief",
    name: "Thief",
    nameRu: "Вор",
    class: "Rangers",
    classRu: "Следопыт",
    status: "None",
    level: "_ENTRY",
    skills: ["stealth", "sleight-of-hand", "pick-lock", "climb"],
    talents: ["alley-cat", "light-fingers"],
    characteristics: { ag: 10 },
  },
  {
    id: "toll-keeper",
    name: "Toll Keeper",
    nameRu: "Сборщик податей",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: [
      "perception",
      "persuade",
      "common-knowledge-reikkland",
      "literacy",
    ],
    talents: ["dealer", "shrewd"],
    characteristics: { int: 10 },
  },
  {
    id: "townsman",
    name: "Townsman",
    nameRu: "Горожанин",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["gossip", "charm", "common-knowledge-reikkland", "dodge"],
    talents: ["suave", "subterfuge"],
    characteristics: { fel: 10 },
  },
  {
    id: "trader",
    name: "Trader",
    nameRu: "Торговец",
    class: "Citizens",
    classRu: "Горожанин",
    status: "Silver 2",
    level: "_ENTRY",
    skills: [
      "trade-merchant",
      "gamble",
      "persuade",
      "common-knowledge-reikkland",
    ],
    talents: ["dealer", "shrewd"],
    characteristics: { fel: 10 },
  },
  {
    id: "vagabond",
    name: "Vagabond",
    nameRu: "Бродяга",
    class: "Rangers",
    classRu: "Следопыт",
    status: "None",
    level: "_ENTRY",
    skills: ["endurance", "outdoor-survival", "athletics", "stealth"],
    talents: ["seasoned-traveller", "strong-back"],
    characteristics: { t: 10 },
  },
  {
    id: "valet",
    name: "Valet",
    nameRu: "Камердинер",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["charm", "dodge", "disguise", "stealth"],
    talents: ["subterfuge", "light-fingers"],
    characteristics: { ag: 10 },
  },
  {
    id: "village-councillor",
    name: "Village Councillor",
    nameRu: "Сельский староста",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "Silver 1",
    level: "_ENTRY",
    skills: [
      "leadership",
      "persuade",
      "common-knowledge-reikkland",
      "literacy",
    ],
    talents: ["dealer", "shrewd"],
    characteristics: { fel: 10 },
  },
  {
    id: "villager",
    name: "Villager",
    nameRu: "Сельский житель",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: ["animal-care", "endurance", "outdoor-survival", "athletics"],
    talents: ["hardy", "strong-back"],
    characteristics: { t: 10 },
  },
  {
    id: "wanderer",
    name: "Wanderer",
    nameRu: "Странник",
    class: "Rangers",
    classRu: "Следопыт",
    status: "None",
    level: "_ENTRY",
    skills: ["outdoor-survival", "navigation", "endurance", "stealth"],
    talents: ["seasoned-traveller", "vagrant"],
    characteristics: { ag: 10 },
  },
  {
    id: "wardog-handler",
    name: "Wardog Handler",
    nameRu: "Проводник боевых псов",
    class: "Military",
    classRu: "Военный",
    status: "None",
    level: "_ENTRY",
    skills: ["charm-animal", "track", "intimidate", "animal-care"],
    talents: ["animal-affinity", "war-dog"],
    characteristics: { wp: 10 },
  },
  {
    id: "watchman",
    name: "Watchman",
    nameRu: "Сторож",
    class: "Citizens",
    classRu: "Горожанин",
    status: "None",
    level: "_ENTRY",
    skills: ["perception", "dodge", "common-knowledge-reikkland", "intimidate"],
    talents: ["watchman", "battle-hardened"],
    characteristics: { i: 10 },
  },
  {
    id: "witch-hunter",
    name: "Witch Hunter",
    nameRu: "Охотник на ведьм",
    class: "Military",
    classRu: "Военный",
    status: "None",
    level: "_ENTRY",
    skills: ["perception", "search", "intimidate", "literacy"],
    talents: ["second-sight", "strong-mind"],
    characteristics: { wp: 10 },
  },
  {
    id: "wizard",
    name: "Wizard",
    nameRu: "Маг",
    class: "Academics",
    classRu: "Академик",
    status: "None",
    level: "_ENTRY",
    skills: ["language-additional", "magical-awareness", "perception", "charm"],
    talents: ["petty-magic", "arcane-magic"],
    characteristics: { int: 10 },
  },
  {
    id: "woodsman",
    name: "Woodsman",
    nameRu: "Лесоруб",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: ["trade-woodchopper", "athletics", "endurance", "outdoor-survival"],
    talents: ["burly", "strong-back"],
    characteristics: { s: 10 },
  },
  {
    id: "yeoman",
    name: "Yeoman",
    nameRu: "Фермер",
    class: "Peasantry",
    classRu: "Крестьянин",
    status: "None",
    level: "_ENTRY",
    skills: ["trade-farmer", "animal-care", "outdoor-survival", "hunt"],
    talents: ["strong-back", "hardy"],
    characteristics: { t: 10 },
  },
];

export const getCareerById = (id: string): Career | undefined =>
  CAREERS.find((c) => c.id === id);

export const CAREER_CLASSES = [
  "Academics",
  "Citizens",
  "Entertainers",
  "Military",
  "Nobles",
  "Peasantry",
  "Rangers",
  "Riverfolk",
];

export const getCareersByClass = (className: string): Career[] =>
  CAREERS.filter((c) => c.class === className);
