export type Skill = {
  id: string;
  name: string;
  nameRu: string;
  characteristic: string;
  description: string;
};

export const SKILLS: Skill[] = [
  {
    id: "animal-care",
    name: "Animal Care",
    nameRu: "Уход за животными",
    characteristic: "int",
    description: "Caring for and handling animals",
  },
  {
    id: "art",
    name: "Art",
    nameRu: "Искусство",
    characteristic: "dex",
    description: "Creating art of any kind",
  },
  {
    id: "athletics",
    name: "Athletics",
    nameRu: "Атлетика",
    characteristic: "ag",
    description: "Climbing, jumping, swimming",
  },
  {
    id: "bribery",
    name: "Bribery",
    nameRu: "Взятки",
    characteristic: "fel",
    description: "Offering bribes to NPCs",
  },
  {
    id: "charm",
    name: "Charm",
    nameRu: "Обольщение",
    characteristic: "fel",
    description: "Persuading others through social means",
  },
  {
    id: "charm-animal",
    name: "Charm Animal",
    nameRu: "Обарание животных",
    characteristic: "wp",
    description: "Influencing animals",
  },
  {
    id: "climb",
    name: "Climb",
    nameRu: "Лазание",
    characteristic: "s",
    description: "Climbing surfaces",
  },
  {
    id: "close-combat-basic",
    name: "Basic Combat Training",
    nameRu: "Базовое боевая подготовка",
    characteristic: "ws",
    description: "Basic melee weapons",
  },
  {
    id: "close-combat-brawling",
    name: "Brawling",
    nameRu: "Драка",
    characteristic: "ws",
    description: "Unarmed combat",
  },
  {
    id: "close-combat-cavalry",
    name: "Cavalry Combat Training",
    nameRu: "Кавалерийский бой",
    characteristic: "ws",
    description: "Melee from horseback",
  },
  {
    id: "close-combat-fencing",
    name: "Fencing",
    nameRu: "Фехтование",
    characteristic: "ws",
    description: "Light melee weapons",
  },
  {
    id: "close-combat-flail",
    name: "Flail",
    nameRu: "Кнут/Цеп",
    characteristic: "ws",
    description: "Flail weapons",
  },
  {
    id: "close-combat-parry",
    name: "Parry",
    nameRu: "Парирование",
    characteristic: "ws",
    description: "Defensive melee combat",
  },
  {
    id: "close-combat-polearm",
    name: "Polearm",
    nameRu: "Древковое оружие",
    characteristic: "ws",
    description: "Polearm weapons",
  },
  {
    id: "close-combat-two-handed",
    name: "Two-Handed Combat",
    nameRu: "Двуручное оружие",
    characteristic: "ws",
    description: "Two-handed melee weapons",
  },
  {
    id: "common-knowledge-bretonnia",
    name: "Common Knowledge: Bretonnia",
    nameRu: "Общие знания: Бретонния",
    characteristic: "int",
    description: "Knowledge of Bretonnia",
  },
  {
    id: "common-knowledge-dwarfs",
    name: "Common Knowledge: Dwarfs",
    nameRu: "Общие знания: Гномы",
    characteristic: "int",
    description: "Knowledge of dwarves",
  },
  {
    id: "common-knowledge-elves",
    name: "Common Knowledge: Elves",
    nameRu: "Общие знания: Эльфы",
    characteristic: "int",
    description: "Knowledge of elves",
  },
  {
    id: "common-knowledge-halflings",
    name: "Common Knowledge: Halflings",
    nameRu: "Общие знания: Хафлинги",
    characteristic: "int",
    description: "Knowledge of halflings",
  },
  {
    id: "common-knowledge-reikkland",
    name: "Common Knowledge: Reikland",
    nameRu: "Общие знания: Рейкланд",
    characteristic: "int",
    description: "Knowledge of the Reikland province",
  },
  {
    id: "common-knowledge-wasteland",
    name: "Common Knowledge: The Wasteland",
    nameRu: "Общие знания: Пустоши",
    characteristic: "int",
    description: "Knowledge of the Wasteland",
  },
  {
    id: "consume-alcohol",
    name: "Consume Alcohol",
    nameRu: "Потребление алкоголя",
    characteristic: "t",
    description: "Holding your drink",
  },
  {
    id: "dodge",
    name: "Dodge",
    nameRu: "Уклонение",
    characteristic: "ag",
    description: "Avoiding attacks",
  },
  {
    id: "drive-cart",
    name: "Drive Cart",
    nameRu: "Управление повозкой",
    characteristic: "ag",
    description: "Driving animal-drawn vehicles",
  },
  {
    id: "endurance",
    name: "Endurance",
    nameRu: "Выносливость",
    characteristic: "t",
    description: "Resisting fatigue and strain",
  },
  {
    id: "entertain-singing",
    name: "Singing",
    nameRu: "Пение",
    characteristic: "fel",
    description: "Singing songs",
  },
  {
    id: "entertain-storytelling",
    name: "Storytelling",
    nameRu: "Рассказывание историй",
    characteristic: "fel",
    description: "Telling stories",
  },
  {
    id: "entertain-string-instruments",
    name: "String Instruments",
    nameRu: "Струнные инструменты",
    characteristic: "dex",
    description: "Playing string instruments",
  },
  {
    id: "entertain-wind-instruments",
    name: "Wind Instruments",
    nameRu: "Духовые инструменты",
    characteristic: "dex",
    description: "Playing wind instruments",
  },
  {
    id: "gamble",
    name: "Gamble",
    nameRu: "Азартные игры",
    characteristic: "int",
    description: "Playing games of chance",
  },
  {
    id: "guess-height",
    name: "Guess Height",
    nameRu: "Оценка роста",
    characteristic: "int",
    description: "Estimating measurements",
  },
  {
    id: "heal",
    name: "Heal",
    nameRu: "Лечение",
    characteristic: "int",
    description: "Treating wounds and illness",
  },
  {
    id: "intimidate",
    name: "Intimidate",
    nameRu: "Запугивание",
    characteristic: "s",
    description: "Frightening others",
  },
  {
    id: "language-additional",
    name: "Additional Language",
    nameRu: "Дополнительный язык",
    characteristic: "int",
    description: "Speaking another language",
  },
  {
    id: "language-aeltharin",
    name: "Language: Aeltharin",
    nameRu: "Язык: Эльтарин",
    characteristic: "int",
    description: "Elven language",
  },
  {
    id: "language-gnomish",
    name: "Language: Gnomish",
    nameRu: "Язык: Гномий",
    characteristic: "int",
    description: "Gnomish language",
  },
  {
    id: "language-khazalid",
    name: "Language: Khazalid",
    nameRu: "Язык: Хазалид",
    characteristic: "int",
    description: "Dwarven language",
  },
  {
    id: "language-old-reikspiel",
    name: "Language: Old Reikspiel",
    nameRu: "Язык: Старый Рейкшпиль",
    characteristic: "int",
    description: "Ancient Reikspiel",
  },
  {
    id: "language-wester",
    name: "Language: Wester",
    nameRu: "Язык: Вестер",
    characteristic: "int",
    description: "Wester language",
  },
  {
    id: "leadership",
    name: "Leadership",
    nameRu: "Лидерство",
    characteristic: "fel",
    description: "Commanding others",
  },
  {
    id: "literacy",
    name: "Literacy",
    nameRu: "Грамотность",
    characteristic: "int",
    description: "Reading and writing",
  },
  {
    id: "magical-awareness",
    name: "Magical Awareness",
    nameRu: "Магическое осознание",
    characteristic: "int",
    description: "Sensing magic",
  },
  {
    id: "melee-basic",
    name: "Melee (Basic)",
    nameRu: "Ближний бой (Базовый)",
    characteristic: "ws",
    description: "Basic melee weapons",
  },
  {
    id: "melee-cavalry",
    name: "Melee (Cavalry)",
    nameRu: "Ближний бой (Кавалерия)",
    characteristic: "ws",
    description: "Melee from horseback",
  },
  {
    id: "melee-fencing",
    name: "Melee (Fencing)",
    nameRu: "Ближний бой (Фехтование)",
    characteristic: "ws",
    description: "Light melee weapons",
  },
  {
    id: "melee-flail",
    name: "Melee (Flail)",
    nameRu: "Ближний бой (Кнут/Цеп)",
    characteristic: "ws",
    description: "Flail weapons",
  },
  {
    id: "melee-polearm",
    name: "Melee (Polearm)",
    nameRu: "Ближний бой (Древковое)",
    characteristic: "ws",
    description: "Polearm weapons",
  },
  {
    id: "melee-two-handed",
    name: "Melee (Two-Handed)",
    nameRu: "Ближний бой (Двуручное)",
    characteristic: "ws",
    description: "Two-handed weapons",
  },
  {
    id: "navigation",
    name: "Navigation",
    nameRu: "Навигация",
    characteristic: "int",
    description: "Finding your way",
  },
  {
    id: "outdoor-survival",
    name: "Outdoor Survival",
    nameRu: "Выживание в дикой природе",
    characteristic: "int",
    description: "Surviving in the wild",
  },
  {
    id: "perception",
    name: "Perception",
    nameRu: "Восприятие",
    characteristic: "i",
    description: "Noticing things",
  },
  {
    id: "pick-lock",
    name: "Pick Lock",
    nameRu: "Взлом замков",
    characteristic: "dex",
    description: "Opening locks",
  },
  {
    id: "pray",
    name: "Pray",
    nameRu: "Молитва",
    characteristic: "wp",
    description: "Religious devotions",
  },
  {
    id: "ride-horse",
    name: "Ride Horse",
    nameRu: "Верховая езда",
    characteristic: "ag",
    description: "Riding horses",
  },
  {
    id: "row",
    name: "Row",
    nameRu: "Гребля",
    characteristic: "s",
    description: "Rowing boats",
  },
  {
    id: "sail",
    name: "Sail",
    nameRu: "Мореплавание",
    characteristic: "ag",
    description: "Sailing boats",
  },
  {
    id: "search",
    name: "Search",
    nameRu: "Обыск",
    characteristic: "int",
    description: "Finding hidden things",
  },
  {
    id: "set-traps",
    name: "Set Traps",
    nameRu: "Установка ловушек",
    characteristic: "dex",
    description: "Setting and disarming traps",
  },
  {
    id: "sleight-of-hand",
    name: "Sleight of Hand",
    nameRu: "Ловкость рук",
    characteristic: "dex",
    description: "Pickpocketing and hidden actions",
  },
  {
    id: "speak-additional-language",
    name: "Speak Additional Language",
    nameRu: "Дополнительный язык",
    characteristic: "int",
    description: "Speaking another language",
  },
  {
    id: "speak-language",
    name: "Speak Language (Native)",
    nameRu: "Родной язык",
    characteristic: "int",
    description: "Speaking your native language",
  },
  {
    id: "trade-acrobat",
    name: "Trade (Acrobat)",
    nameRu: "Ремесло: Акробат",
    characteristic: "ag",
    description: "Acrobatics trade",
  },
  {
    id: "trade-alchemist",
    name: "Trade (Alchemist)",
    nameRu: "Ремесло: Алхимик",
    characteristic: "int",
    description: "Alchemy trade",
  },
  {
    id: "trade-animal-dealer",
    name: "Trade (Animal Dealer)",
    nameRu: "Ремесло: Торговец животными",
    characteristic: "fel",
    description: "Animal dealing trade",
  },
  {
    id: "trade-apothecary",
    name: "Trade (Apothecary)",
    nameRu: "Ремесло: Аптекарь",
    characteristic: "int",
    description: "Apothecary trade",
  },
  {
    id: "trade-armourer",
    name: "Trade (Armourer)",
    nameRu: "Ремесло: Бронник",
    characteristic: "int",
    description: "Armourer trade",
  },
  {
    id: "trade-blacksmith",
    name: "Trade (Blacksmith)",
    nameRu: "Ремесло: Кузнец",
    characteristic: "s",
    description: "Blacksmith trade",
  },
  {
    id: "trade-bowyer",
    name: "Trade (Bowyer)",
    nameRu: "Ремесло: Лукарь",
    characteristic: "dex",
    description: "Bowyer trade",
  },
  {
    id: "trade-brewer",
    name: "Trade (Brewer)",
    nameRu: "Ремесло: Пивовар",
    characteristic: "int",
    description: "Brewer trade",
  },
  {
    id: "trade-builder",
    name: "Trade (Builder)",
    nameRu: "Ремесло: Строитель",
    characteristic: "int",
    description: "Builder trade",
  },
  {
    id: "trade-butcher",
    name: "Trade (Butcher)",
    nameRu: "Ремесло: Мясник",
    characteristic: "int",
    description: "Butcher trade",
  },
  {
    id: "trade-carrier",
    name: "Trade (Carrier)",
    nameRu: "Ремесло: Перевозчик",
    characteristic: "ag",
    description: "Carrier trade",
  },
  {
    id: "trade-cook",
    name: "Trade (Cook)",
    nameRu: "Ремесло: Повар",
    characteristic: "int",
    description: "Cook trade",
  },
  {
    id: "trade-carpenter",
    name: "Trade (Carpenter)",
    nameRu: "Ремесло: Плотник",
    characteristic: "dex",
    description: "Carpenter trade",
  },
  {
    id: "trade-cobbler",
    name: "Trade (Cobbler)",
    nameRu: "Ремесло: Сапожник",
    characteristic: "dex",
    description: "Cobbler trade",
  },
  {
    id: "trade-driver",
    name: "Trade (Wagon Driver)",
    nameRu: "Ремесло: Возничий",
    characteristic: "ag",
    description: "Wagon driver trade",
  },
  {
    id: "trade-fletch",
    name: "Trade (Fletcher)",
    nameRu: "Ремесло: Мастер стрел",
    characteristic: "dex",
    description: "Fletcher trade",
  },
  {
    id: "trade-herbalist",
    name: "Trade (Herbalist)",
    nameRu: "Ремесло: Травник",
    characteristic: "int",
    description: "Herbalist trade",
  },
  {
    id: "trade-hunter",
    name: "Trade (Hunter)",
    nameRu: "Ремесло: Охотник",
    characteristic: "int",
    description: "Hunter trade",
  },
  {
    id: "trade-mason",
    name: "Trade (Mason)",
    nameRu: "Ремесло: Каменщик",
    characteristic: "dex",
    description: "Mason trade",
  },
  {
    id: "trade-merchant",
    name: "Trade (Merchant)",
    nameRu: "Ремесло: Купец",
    characteristic: "fel",
    description: "Merchant trade",
  },
  {
    id: "trade-miner",
    name: "Trade (Miner)",
    nameRu: "Ремесло: Шахтёр",
    characteristic: "s",
    description: "Miner trade",
  },
  {
    id: "trade-music",
    name: "Trade (Musician)",
    nameRu: "Ремесло: Музыкант",
    characteristic: "dex",
    description: "Musician trade",
  },
  {
    id: "trade-peddler",
    name: "Trade (Peddler)",
    nameRu: "Ремесло: Торговец",
    characteristic: "fel",
    description: "Peddler trade",
  },
  {
    id: "trader-shipwright",
    name: "Trade (Shipwright)",
    nameRu: "Ремесло: Корабельный мастер",
    characteristic: "int",
    description: "Shipwright trade",
  },
  {
    id: "trade-tailor",
    name: "Trade (Tailor)",
    nameRu: "Ремесло: Портной",
    characteristic: "dex",
    description: "Tailor trade",
  },
  {
    id: "trade-tanner",
    name: "Trade (Tanner)",
    nameRu: "Ремесло: Дубщик",
    characteristic: "int",
    description: "Tanner trade",
  },
  {
    id: "trade-weapon",
    name: "Trade (Weapon Smith)",
    nameRu: "Ремесло: Оружейник",
    characteristic: "dex",
    description: "Weapon smith trade",
  },
  {
    id: "tracking",
    name: "Tracking",
    nameRu: "Следопытство",
    characteristic: "int",
    description: "Following tracks",
  },
  {
    id: "warfare-tactics",
    name: "Warfare Tactics",
    nameRu: "Военная тактика",
    characteristic: "int",
    description: "Military tactics",
  },
];

export const getSkillById = (id: string): Skill | undefined =>
  SKILLS.find((s) => s.id === id);
