export type Talent = {
  id: string;
  name: string;
  nameRu: string;
  description: string;
  maxRank?: number;
  tests?: string;
};

export const TALENTS: Talent[] = [
  {
    id: "aethyric-attunement",
    name: "Aethyric Attunement",
    nameRu: "Эфирная гармония",
    description: "You can sense and manipulate aethyric energy more easily",
    maxRank: 1,
  },
  {
    id: "alley-cat",
    name: "Alley Cat",
    nameRu: "Кот из подворотни",
    description:
      "You can see in dim light and can always run at full speed through narrow spaces",
    maxRank: 1,
  },
  {
    id: "ambidextrous",
    name: "Ambidextrous",
    nameRu: "Амбидекстр",
    description: "You can use both hands equally well",
    maxRank: 1,
  },
  {
    id: "animal-affinity",
    name: "Animal Affinity",
    nameRu: "Связь с животными",
    description: "You have a natural bond with animals",
    maxRank: 1,
  },
  {
    id: "arcane-magic",
    name: "Arcane Magic",
    nameRu: "Магическая аура",
    description: "You can cast arcane spells",
    maxRank: 1,
  },
  {
    id: "battle-rage",
    name: "Battle Rage",
    nameRu: "Боевой ярость",
    description: "You can enter a rage in combat",
    maxRank: 1,
  },
  {
    id: "blather",
    name: "Blather",
    nameRu: "Болтовня",
    description: "You can distract with meaningless chatter",
    maxRank: 1,
  },
  {
    id: "blood-of-the-mountain",
    name: "Blood of the Mountain",
    nameRu: "Кровь горы",
    description: "You are adapted to living in mountains and underground",
    maxRank: 1,
  },
  {
    id: "bookish",
    name: "Bookish",
    nameRu: "Книжник",
    description: "You gain a bonus to Literacy tests",
    maxRank: 1,
  },
  {
    id: "bound-to-the-wild",
    name: "Bound to the Wild",
    nameRu: "Связанный с природой",
    description: "You are at home in the wilderness",
    maxRank: 1,
  },
  {
    id: "brazen",
    name: "Brazen",
    nameRu: "Дерзкий",
    description: "You can Intimidate more effectively",
    maxRank: 1,
  },
  {
    id: "bright",
    name: "Bright",
    nameRu: "Светлый",
    description: "You learn languages more easily",
    maxRank: 1,
  },
  {
    id: "carouser",
    name: "Carouser",
    nameRu: "Кутила",
    description: "You can drink more than most",
    maxRank: 1,
  },
  {
    id: "catalyst",
    name: "Catalyst",
    nameRu: "Катализатор",
    description: "You are a conduit for mutation",
    maxRank: 1,
  },
  {
    id: "cautious",
    name: "Cautious",
    nameRu: "Осторожный",
    description: "You can take extra time to avoid traps",
    maxRank: 1,
  },
  {
    id: "charismatic",
    name: "Charismatic",
    nameRu: "Харизматичный",
    description: "You can Lead more effectively",
    maxRank: 1,
  },
  {
    id: "charm",
    name: "Charm",
    nameRu: "Обаяние",
    description: "You can Charm others more easily",
    maxRank: 1,
  },
  {
    id: "cherubic",
    name: "Cherubic",
    nameRu: "Херувим",
    description: "You look innocent and trustworthy",
    maxRank: 1,
  },
  {
    id: "climber",
    name: "Climber",
    nameRu: "Альпинист",
    description: "You can climb more easily",
    maxRank: 1,
  },
  {
    id: "cold-blooded",
    name: "Cold Blooded",
    nameRu: "Хладнокровный",
    description: "You can remain calm under pressure",
    maxRank: 1,
  },
  {
    id: "combat-reflexes",
    name: "Combat Reflexes",
    nameRu: "Боевые рефлексы",
    description: "You react faster in combat",
    maxRank: 1,
  },
  {
    id: "cool-headed-or-resolute",
    name: "Cool Headed / Resolute",
    nameRu: "Хладнокровный / Стойкий",
    description: "You can resist fear and maintain composure",
    maxRank: 1,
  },
  {
    id: "craftsman",
    name: "Craftsman",
    nameRu: "Ремесленник",
    description: "You can make items more easily",
    maxRank: 1,
  },
  {
    id: "crippling-blows",
    name: "Crippling Blows",
    nameRu: "Калечащие удары",
    description: "Your attacks can cause more damage",
    maxRank: 1,
  },
  {
    id: "cunning",
    name: "Cunning",
    nameRu: "Хитрость",
    description: "You can see through deception",
    maxRank: 1,
  },
  {
    id: "curiosity",
    name: "Curiosity",
    nameRu: "Любопытство",
    description: "You gain a bonus to Perception tests",
    maxRank: 1,
  },
  {
    id: "darksight",
    name: "Darksight",
    nameRu: "Ночное зрение",
    description: "You can see in complete darkness",
    maxRank: 1,
  },
  {
    id: "deadeye-shot",
    name: "Deadeye Shot",
    nameRu: "Меткий глаз",
    description: "You can make more accurate ranged attacks",
    maxRank: 1,
  },
  {
    id: "death-blow",
    name: "Death Blow",
    nameRu: "Смертельный удар",
    description: "You can make killing blows more easily",
    maxRank: 1,
  },
  {
    id: "defensive-fighting",
    name: "Defensive Fighting",
    nameRu: "Оборонительный бой",
    description: "You can defend more effectively",
    maxRank: 1,
  },
  {
    id: "desert-fox",
    name: "Desert Fox",
    nameRu: "Пустынная лиса",
    description: "You are adapted to desert conditions",
    maxRank: 1,
  },
  {
    id: "devastating-blow",
    name: "Devastating Blow",
    nameRu: "Разрушительный удар",
    description: "You can deal massive damage",
    maxRank: 1,
  },
  {
    id: "dirty-fighting",
    name: "Dirty Fighting",
    nameRu: "Грязный бой",
    description: "You can fight dirty in combat",
    maxRank: 1,
  },
  {
    id: "disarm",
    name: "Disarm",
    nameRu: "Разоружение",
    description: "You can disarm opponents",
    maxRank: 1,
  },
  {
    id: "distract",
    name: "Distract",
    nameRu: "Отвлечение",
    description: "You can distract enemies in combat",
    maxRank: 1,
  },
  {
    id: "dragon-blood",
    name: "Dragon Blood",
    nameRu: "Драконья кровь",
    description: "You have resistance to fire",
    maxRank: 1,
  },
  {
    id: "drilled",
    name: "Drilled",
    nameRu: "Тренированный",
    description: "You can use Formation Fighting",
    maxRank: 1,
  },
  {
    id: "dual-shot",
    name: "Dual Shot",
    nameRu: "Двойной выстрел",
    description: "You can fire two weapons at once",
    maxRank: 1,
  },
  {
    id: "eagle-eyed",
    name: "Eagle-Eyed",
    nameRu: "Орлиный глаз",
    description: "You can see great distances",
    maxRank: 1,
  },
  {
    id: "enchanter",
    name: "Enchanter",
    nameRu: "Чародей",
    description: "You can imbue items with magic",
    maxRank: 1,
  },
  {
    id: "enraging-blow",
    name: "Enraging Blow",
    nameRu: "Гневный удар",
    description: "Your attacks can cause rage",
    maxRank: 1,
  },
  {
    id: "escape-artist",
    name: "Escape Artist",
    nameRu: "Мастер побега",
    description: "You can escape from bonds",
    maxRank: 1,
  },
  {
    id: "eternal-hunger",
    name: "Eternal Hunger",
    nameRu: "Вечный голод",
    description: "You are cursed with unending hunger",
    maxRank: 1,
  },
  {
    id: "ever-lasting",
    name: "Ever Lasting",
    nameRu: "Вечный",
    description: "You do not age",
    maxRank: 1,
  },
  {
    id: "face-in-crowd",
    name: "Face in the Crowd",
    nameRu: "Лицо в толпе",
    description: "You can hide in crowds",
    maxRank: 1,
  },
  {
    id: "fast-hands",
    name: "Fast Hands",
    nameRu: "Быстрые руки",
    description: "You can perform actions more quickly",
    maxRank: 1,
  },
  {
    id: "fearless",
    name: "Fearless",
    nameRu: "Бесстрашный",
    description: "You cannot be afraid",
    maxRank: 1,
  },
  {
    id: "feral-children",
    name: "Feral Children",
    nameRu: "Дикие дети",
    description: "You were raised by animals",
    maxRank: 1,
  },
  {
    id: "field-dressing",
    name: "Field Dressing",
    nameRu: "Полевой перевязочный",
    description: "You can treat wounds on the battlefield",
    maxRank: 1,
  },
  {
    id: "fighting-finesse",
    name: "Fighting Finesse",
    nameRu: "Боевое изящество",
    description: "You can use Agility instead of Strength in melee",
    maxRank: 1,
  },
  {
    id: "flame-dancer",
    name: "Flame Dancer",
    nameRu: "Танцор огня",
    description: "You are immune to fire",
    maxRank: 1,
  },
  {
    id: "fleet-footed",
    name: "Fleet Footed",
    nameRu: "Быстроногий",
    description: "You can run faster",
    maxRank: 1,
  },
  {
    id: "frenzy",
    name: "Frenzy",
    nameRu: "Безумие",
    description: "You can enter a frenzy in combat",
    maxRank: 1,
  },
  {
    id: "frostbite",
    name: "Frostbite",
    nameRu: "Обморожение",
    description: "You are adapted to cold climates",
    maxRank: 1,
  },
  {
    id: "giant-blood",
    name: "Giant Blood",
    nameRu: "Кровь великана",
    description: "You are larger than most",
    maxRank: 1,
  },
  {
    id: "goblin-skulker",
    name: "Goblin Skulker",
    nameRu: "Гоблин-скрытник",
    description: "You can hide easily",
    maxRank: 1,
  },
  {
    id: "gravetouched",
    name: "Gravetouched",
    nameRu: "Прикосновение могилы",
    description: "You are connected to the undead",
    maxRank: 1,
  },
  {
    id: "greed",
    name: "Greed",
    nameRu: "Жадность",
    description: "You can find treasure more easily",
    maxRank: 1,
  },
  {
    id: "gregarious",
    name: "Gregarious",
    nameRu: "Общительный",
    description: "You can Charm groups",
    maxRank: 1,
  },
  {
    id: "grim-composure",
    name: "Grim Composure",
    nameRu: "Мрачная стойкость",
    description: "You can resist psychological effects",
    maxRank: 1,
  },
  {
    id: "guerrilla",
    name: "Guerrilla",
    nameRu: "Партизан",
    description: "You are skilled in guerrilla warfare",
    maxRank: 1,
  },
  {
    id: "gun-fighter",
    name: "Gun Fighter",
    nameRu: "Стрелок",
    description: "You can fire ranged weapons more easily",
    maxRank: 1,
  },
  {
    id: "hardy",
    name: "Hardy",
    nameRu: "Стойкий",
    description: "You can survive more wounds",
    maxRank: 1,
  },
  {
    id: "hatred",
    name: "Hatred",
    nameRu: "Ненависть",
    description: "You have a powerful hatred towards something",
    maxRank: 1,
  },
  {
    id: "healer",
    name: "Healer",
    nameRu: "Целитель",
    description: "You can Heal more effectively",
    maxRank: 1,
  },
  {
    id: "herbalist",
    name: "Herbalist",
    nameRu: "Травник",
    description: "You can create herbal remedies",
    maxRank: 1,
  },
  {
    id: "holy-guardian",
    name: "Holy Guardian",
    nameRu: "Святой страж",
    description: "You are protected by divine power",
    maxRank: 1,
  },
  {
    id: "horn-of-doom",
    name: "Horn of Doom",
    nameRu: "Рог судьбы",
    description: "You can inspire fear in enemies",
    maxRank: 1,
  },
  {
    id: "hunchback",
    name: "Hunchback",
    nameRu: "Горбун",
    description: "You have a hunched back",
    maxRank: 1,
  },
  {
    id: "hunter",
    name: "Hunter",
    nameRu: "Охотник",
    description: "You are skilled at hunting",
    maxRank: 1,
  },
  {
    id: "immortal",
    name: "Immortal",
    nameRu: "Бессмертный",
    description: "You cannot die from old age",
    maxRank: 1,
  },
  {
    id: "impetuous",
    name: "Impetuous",
    nameRu: "Безрассудный",
    description: "You act quickly in combat",
    maxRank: 1,
  },
  {
    id: "implacable",
    name: "Implacable",
    nameRu: "Непреклонный",
    description: "You cannot be stopped once you start something",
    maxRank: 1,
  },
  {
    id: "incorruptible",
    name: "Incorruptible",
    nameRu: "Неподкупный",
    description: "You cannot be corrupted",
    maxRank: 1,
  },
  {
    id: "inspiring",
    name: "Inspiring",
    nameRu: "Вдохновляющий",
    description: "You can inspire others",
    maxRank: 1,
  },
  {
    id: "iron-jaw",
    name: "Iron Jaw",
    nameRu: "Железная челюсть",
    description: "You can take more hits to the head",
    maxRank: 1,
  },
  {
    id: "iron-willed",
    name: "Iron Willed",
    nameRu: "Стальная воля",
    description: "You can resist mental attacks",
    maxRank: 1,
  },
  {
    id: "juggler",
    name: "Juggler",
    nameRu: "Жонглёр",
    description: "You can juggle items",
    maxRank: 1,
  },
  {
    id: "jump",
    name: "Jump",
    nameRu: "Прыжок",
    description: "You can jump further",
    maxRank: 1,
  },
  {
    id: "king-of-the-mountain",
    name: "King of the Mountain",
    nameRu: "Король горы",
    description: "You are at home in mountains",
    maxRank: 1,
  },
  {
    id: "lightning-reflexes",
    name: "Lightning Reflexes",
    nameRu: "Молненные рефлексы",
    description: "You can react faster",
    maxRank: 1,
  },
  {
    id: "linguist",
    name: "Linguist",
    nameRu: "Лингвист",
    description: "You learn languages easily",
    maxRank: 1,
  },
  {
    id: "liver-of-steel",
    name: "Liver of Steel",
    nameRu: "Стальная печень",
    description: "You can resist poison",
    maxRank: 1,
  },
  {
    id: "long-nostril",
    name: "Long Nostril",
    nameRu: "Чуткий нос",
    description: "You can smell things better",
    maxRank: 1,
  },
  {
    id: "lucky",
    name: "Lucky",
    nameRu: "Удачливый",
    description: "You have extra luck points",
    maxRank: 1,
  },
  {
    id: "luminous",
    name: "Luminous",
    nameRu: "Светящийся",
    description: "You emit a soft glow",
    maxRank: 1,
  },
  {
    id: "magical-sensitivity",
    name: "Magical Sensitivity",
    nameRu: "Магическая чувствительность",
    description: "You can sense magic",
    maxRank: 1,
  },
  {
    id: "magnum-bullet",
    name: "Magnum Bullet",
    nameRu: "Магнум пуля",
    description: "You can load more powerful ammunition",
    maxRank: 1,
  },
  {
    id: "man-uncouth",
    name: "Man Uncouth",
    nameRu: "Грубиян",
    description: "You are naturally intimidating",
    maxRank: 1,
  },
  {
    id: "marksman",
    name: "Marksman",
    nameRu: "Стрелок",
    description: "You can aim for weak points",
    maxRank: 1,
  },
  {
    id: "master-of-balance",
    name: "Master of Balance",
    nameRu: "Мастер баланса",
    description: "You can maintain balance easily",
    maxRank: 1,
  },
  {
    id: "master-tradesman",
    name: "Master Tradesman",
    nameRu: "Мастер ремесла",
    description: "You can create masterwork items",
    maxRank: 1,
  },
  {
    id: "medic",
    name: "Medic",
    nameRu: "Медик",
    description: "You can treat wounds more effectively",
    maxRank: 1,
  },
  {
    id: "menacing",
    name: "Menacing",
    nameRu: "Угрожающий",
    description: "You can Intimidate more easily",
    maxRank: 1,
  },
  {
    id: "mimic",
    name: "Mimic",
    nameRu: "Имитатор",
    description: "You can mimic sounds",
    maxRank: 1,
  },
  {
    id: "minimus-herbalist",
    name: "Minimus Herbalist",
    nameRu: "Травник",
    description: "You can create healing remedies",
    maxRank: 1,
  },
  {
    id: "miracle-worker",
    name: "Miracle Worker",
    nameRu: "Чудотворец",
    description: "You can perform miracles",
    maxRank: 1,
  },
  {
    id: "miser",
    name: "Miser",
    nameRu: "Скупец",
    description: "You can find treasure more easily",
    maxRank: 1,
  },
  {
    id: "mongrel",
    name: "Mongrel",
    nameRu: "Полукровка",
    description: "You can eat anything",
    maxRank: 1,
  },
  {
    id: "mountain-blood",
    name: "Mountain Blood",
    nameRu: "Горная кровь",
    description: "You are adapted to mountains",
    maxRank: 1,
  },
  {
    id: "mummy",
    name: "Mummy",
    nameRu: "Мумия",
    description: "You are undead",
    maxRank: 1,
  },
  {
    id: "murderer",
    name: "Murderer",
    nameRu: "Убийца",
    description: "You can make killing blows more easily",
    maxRank: 1,
  },
  {
    id: "mutation",
    name: "Mutation",
    nameRu: "Мутация",
    description: "You have a mutation",
    maxRank: 3,
  },
  {
    id: "naked-blade",
    name: "Naked Blade",
    nameRu: "Голый клинок",
    description: "You can fight without armor",
    maxRank: 1,
  },
  {
    id: "navigators-sense",
    name: "Navigator's Sense",
    nameRu: "Чувство навигатора",
    description: "You can always find your way",
    maxRank: 1,
  },
  {
    id: "night-vision",
    name: "Night Vision",
    nameRu: "Ночное зрение",
    description: "You can see in darkness",
    maxRank: 1,
  },
  {
    id: "nimble-fingered",
    name: "Nimble Fingered",
    nameRu: "Проворные пальцы",
    description: "You can pick locks and pockets easily",
    maxRank: 1,
  },
  {
    id: "nose-for-business",
    name: "Nose for Business",
    nameRu: "Нюх на дела",
    description: "You can find opportunities to make money",
    maxRank: 1,
  },
  {
    id: "old-soldier",
    name: "Old Soldier",
    nameRu: "Ветеран",
    description: "You are experienced in warfare",
    maxRank: 1,
  },
  {
    id: "oracle",
    name: "Oracle",
    nameRu: "Оракул",
    description: "You can predict the future",
    maxRank: 1,
  },
  {
    id: "outlander",
    name: "Outlander",
    nameRu: "Пришелец",
    description: "You are from the wilderness",
    maxRank: 1,
  },
  {
    id: "pack-hunter",
    name: "Pack Hunter",
    nameRu: "Стайный охотник",
    description: "You work well in groups",
    maxRank: 1,
  },
  {
    id: "panhandle",
    name: "Panhandle",
    nameRu: "Попрошайничество",
    description: "You can beg for money",
    maxRank: 1,
  },
  {
    id: "patient",
    name: "Patient",
    nameRu: "Терпеливый",
    description: "You can wait for the right moment",
    maxRank: 1,
  },
  {
    id: "perfect-ripost",
    name: "Perfect Ripost",
    nameRu: "Идеальная контратака",
    description: "You can counterattack perfectly",
    maxRank: 1,
  },
  {
    id: "pestilent-flesh",
    name: "Pestilent Flesh",
    nameRu: "Чумная плоть",
    description: "You are infected with disease",
    maxRank: 1,
  },
  {
    id: "petty-magic",
    name: "Petty Magic",
    nameRu: "Малая магия",
    description: "You can cast petty magic",
    maxRank: 1,
  },
  {
    id: "phobias",
    name: "Phobias",
    nameRu: "Фобия",
    description: "You have a phobia",
    maxRank: 3,
  },
  {
    id: "pirate",
    name: "Pirate",
    nameRu: "Пират",
    description: "You are skilled at sea combat",
    maxRank: 1,
  },
  {
    id: "pistolier",
    name: "Pistolier",
    nameRu: "Пистолетник",
    description: "You can fire pistols quickly",
    maxRank: 1,
  },
  {
    id: "pitch-perfect",
    name: "Pitch Perfect",
    nameRu: "Идеальный слух",
    description: "You have perfect pitch",
    maxRank: 1,
  },
  {
    id: "plague-bearer",
    name: "Plague Bearer",
    nameRu: "Чумной",
    description: "You carry disease",
    maxRank: 1,
  },
  {
    id: "poacher",
    name: "Poacher",
    nameRu: "Браконьер",
    description: "You can hunt illegally",
    maxRank: 1,
  },
  {
    id: "precise-memory",
    name: "Precise Memory",
    nameRu: "Точная память",
    description: "You remember everything",
    maxRank: 1,
  },
  {
    id: "prehensile-tail",
    name: "Prehensile Tail",
    nameRu: "Цепкий хвост",
    description: "You have a prehensile tail",
    maxRank: 1,
  },
  {
    id: "profane-lore",
    name: "Profane Lore",
    nameRu: "Нечестивое знание",
    description: "You know dark secrets",
    maxRank: 1,
  },
  {
    id: "proper-burial",
    name: "Proper Burial",
    nameRu: "Правильное погребение",
    description: "You know how to bury the dead",
    maxRank: 1,
  },
  {
    id: "pub-fund",
    name: "Pub Fund",
    nameRu: "Кабак",
    description: "You always have money for drinks",
    maxRank: 1,
  },
  {
    id: "quick-draw",
    name: "Quick Draw",
    nameRu: "Быстрый выхват",
    description: "You can draw weapons quickly",
    maxRank: 1,
  },
  {
    id: "quick-shot",
    name: "Quick Shot",
    nameRu: "Быстрый выстрел",
    description: "You can fire quickly",
    maxRank: 1,
  },
  {
    id: "ranged-weapon-specialist",
    name: "Ranged Weapon Specialist",
    nameRu: "Специалист по дальнобойному оружию",
    description: "You can use ranged weapons better",
    maxRank: 1,
  },
  {
    id: "rat-catcher",
    name: "Rat Catcher",
    nameRu: "Истребитель крыс",
    description: "You can catch rats",
    maxRank: 1,
  },
  {
    id: "reclaimed",
    name: "Reclaimed",
    nameRu: "Возрождённый",
    description: "You were formerly chaos corrupted",
    maxRank: 1,
  },
  {
    id: "regeneration",
    name: "Regeneration",
    nameRu: "Регенерация",
    description: "You can heal wounds faster",
    maxRank: 1,
  },
  {
    id: "relentless",
    name: "Relentless",
    nameRu: "Неутомимый",
    description: "You never give up",
    maxRank: 1,
  },
  {
    id: "repellent",
    name: "Repellent",
    nameRu: "Отталкивающий",
    description: "You are naturally unlikable",
    maxRank: 1,
  },
  {
    id: "resilient",
    name: "Resilient",
    nameRu: "Стойкий",
    description: "You can resist damage better",
    maxRank: 1,
  },
  {
    id: "rich-luck",
    name: "Rich Luck",
    nameRu: "Богатая удача",
    description: "You have extra luck points",
    maxRank: 1,
  },
  {
    id: "river-child",
    name: "River Child",
    nameRu: "Речной ребёнок",
    description: "You are at home in rivers",
    maxRank: 1,
  },
  {
    id: "rooted",
    name: "Rooted",
    nameRu: "Укоренившийся",
    description: "You cannot be knocked down",
    maxRank: 1,
  },
  {
    id: "runes",
    name: "Runes",
    nameRu: "Руны",
    description: "You can inscribe runes",
    maxRank: 1,
  },
  {
    id: "sabotage",
    name: "Sabotage",
    nameRu: "Саботаж",
    description: "You can sabotage items",
    maxRank: 1,
  },
  {
    id: "savant",
    name: "Savant",
    nameRu: "Савант",
    description: "You have exceptional knowledge in one area",
    maxRank: 1,
  },
  {
    id: "scavenger",
    name: "Scavenger",
    nameRu: "Мусорщик",
    description: "You can find useful items",
    maxRank: 1,
  },
  {
    id: "seasoned-traveller",
    name: "Seasoned Traveller",
    nameRu: "Бывалый путник",
    description: "You have traveled extensively",
    maxRank: 1,
  },
  {
    id: "second-sight",
    name: "Second Sight",
    nameRu: "Второе зрение",
    description: "You can see the unseen",
    maxRank: 1,
  },
  {
    id: "second-wind",
    name: "Second Wind",
    nameRu: "Второе дыхание",
    description: "You can keep fighting after being knocked down",
    maxRank: 1,
  },
  {
    id: "shadow",
    name: "Shadow",
    nameRu: "Тень",
    description: "You can hide in shadows",
    maxRank: 1,
  },
  {
    id: "sharpshooter",
    name: "Sharpshooter",
    nameRu: "Снайпер",
    description: "You can make precise shots",
    maxRank: 1,
  },
  {
    id: "sixth-sense",
    name: "Sixth Sense",
    nameRu: "Шестое чувство",
    description: "You can sense danger",
    maxRank: 1,
  },
  {
    id: "skilled-rider",
    name: "Skilled Rider",
    nameRu: "Умелый наездник",
    description: "You can ride any mount",
    maxRank: 1,
  },
  {
    id: "sleight-of-mind",
    name: "Sleight of Mind",
    nameRu: "Ловкость ума",
    description: "You can resist mental effects",
    maxRank: 1,
  },
  {
    id: "slippery",
    name: "Slippery",
    nameRu: "Скользкий",
    description: "You can escape from bonds",
    maxRank: 1,
  },
  {
    id: "smash",
    name: "Smash",
    nameRu: "Сокрушение",
    description: "You can destroy objects more easily",
    maxRank: 1,
  },
  {
    id: "song-of-astonishment",
    name: "Song of Astonishment",
    nameRu: "Песня изумления",
    description: "You can amaze with performance",
    maxRank: 1,
  },
  {
    id: "sonic-blast",
    name: "Sonic Blast",
    nameRu: "Звуковая волна",
    description: "You can create sonic blasts",
    maxRank: 1,
  },
  {
    id: "spirit-blood",
    name: "Spirit Blood",
    nameRu: "Духовная кровь",
    description: "You are connected to spirits",
    maxRank: 1,
  },
  {
    id: "squire",
    name: "Squire",
    nameRu: "Оруженосец",
    description: "You are trained in knightly duties",
    maxRank: 1,
  },
  {
    id: "stalker",
    name: "Stalker",
    nameRu: "Следопыт",
    description: "You can track without being noticed",
    maxRank: 1,
  },
  {
    id: "steel-nerves",
    name: "Steel Nerves",
    nameRu: "Стальные нервы",
    description: "You can remain calm under fire",
    maxRank: 1,
  },
  {
    id: "stepping",
    name: "Stepping",
    nameRu: "Шаг",
    description: "You can move between realms",
    maxRank: 1,
  },
  {
    id: "strider",
    name: "Strider",
    nameRu: "Странник",
    description: "You can walk on any surface",
    maxRank: 1,
  },
  {
    id: "strong-minded",
    name: "Strong Minded",
    nameRu: "Сильный духом",
    description: "You can resist mental attacks",
    maxRank: 1,
  },
  {
    id: "strong-swim",
    name: "Strong Swim",
    nameRu: "Сильный пловец",
    description: "You can swim better",
    maxRank: 1,
  },
  {
    id: "sturdy",
    name: "Sturdy",
    nameRu: "Крепкий",
    description: "You are physically strong",
    maxRank: 1,
  },
  {
    id: "suave",
    name: "Suave",
    nameRu: "Утончённый",
    description: "You are naturally charming",
    maxRank: 1,
  },
  {
    id: "subterfuge",
    name: "Subterfuge",
    nameRu: "Интриган",
    description: "You can deceive others",
    maxRank: 1,
  },
  {
    id: "sundancer",
    name: "Sundancer",
    nameRu: "Танцор солнца",
    description: "You are immune to fire",
    maxRank: 1,
  },
  {
    id: "super-numerary",
    name: "Super Numerary",
    nameRu: "Сверхкомплект",
    description: "You can carry more items",
    maxRank: 1,
  },
  {
    id: "suros",
    name: "Su'suros",
    nameRu: "Су'сурос",
    description: "You have a lucky sword",
    maxRank: 1,
  },
  {
    id: "swan-may",
    name: "Swan May",
    nameRu: "Лебедушка",
    description: "You have wings",
    maxRank: 1,
  },
  {
    id: "swashbuckler",
    name: "Swashbuckler",
    nameRu: "Щеголь",
    description: "You can fight with flair",
    maxRank: 1,
  },
  {
    id: "swordbreaker",
    name: "Swordbreaker",
    nameRu: "Мечелом",
    description: "You can break weapons",
    maxRank: 1,
  },
  {
    id: "tenacious",
    name: "Tenacious",
    nameRu: "Упорный",
    description: "You never give up",
    maxRank: 1,
  },
  {
    id: "terror",
    name: "Terror",
    nameRu: "Террор",
    description: "You can inspire terror",
    maxRank: 1,
  },
  {
    id: "thief",
    name: "Thief",
    nameRu: "Вор",
    description: "You are skilled at stealing",
    maxRank: 1,
  },
  {
    id: "third-eye",
    name: "Third Eye",
    nameRu: "Третий глаз",
    description: "You can see magic",
    maxRank: 1,
  },
  {
    id: "thunderous-charge",
    name: "Thunderous Charge",
    nameRu: "Громовая атака",
    description: "Your charges deal more damage",
    maxRank: 1,
  },
  {
    id: "tinker",
    name: "Tinker",
    nameRu: "Ремонтник",
    description: "You can fix items easily",
    maxRank: 1,
  },
  {
    id: "tiring-strike",
    name: "Tiring Strike",
    nameRu: "Утомляющий удар",
    description: "Your attacks tire enemies",
    maxRank: 1,
  },
  {
    id: "tornado-charge",
    name: "Tornado Charge",
    nameRu: "Торнадо",
    description: "You can spin in combat",
    maxRank: 1,
  },
  {
    id: "tracker",
    name: "Tracker",
    nameRu: "Следопыт",
    description: "You can track anything",
    maxRank: 1,
  },
  {
    id: "trader",
    name: "Trader",
    nameRu: "Торговец",
    description: "You can get better prices",
    maxRank: 1,
  },
  {
    id: "trained-animal",
    name: "Trained Animal",
    nameRu: "Дрессированное животное",
    description: "You have a trained animal",
    maxRank: 1,
  },
  {
    id: "trick-riding",
    name: "Trick Riding",
    nameRu: "Трюковая езда",
    description: "You can perform tricks on horseback",
    maxRank: 1,
  },
  {
    id: "trickster",
    name: "Trickster",
    nameRu: "Плут",
    description: "You can play tricks on others",
    maxRank: 1,
  },
  {
    id: "trophy-collector",
    name: "Trophy Collector",
    nameRu: "Коллекционер трофеев",
    description: "You collect trophies",
    maxRank: 1,
  },
  {
    id: "true-aim",
    name: "True Aim",
    nameRu: "Прицельный",
    description: "You can aim for vital spots",
    maxRank: 1,
  },
  {
    id: "tunnel-rat",
    name: "Tunnel Rat",
    nameRu: "Крыса подземелий",
    description: "You are at home in tunnels",
    maxRank: 1,
  },
  {
    id: "twitchy",
    name: "Twitchy",
    nameRu: "Нервный",
    description: "You are always alert",
    maxRank: 1,
  },
  {
    id: "uncanny-resilience",
    name: "Uncanny Resilience",
    nameRu: "Невероятная стойкость",
    description: "You can ignore wounds",
    maxRank: 1,
  },
  {
    id: "unicorn-blood",
    name: "Unicorn Blood",
    nameRu: "Кровь единорога",
    description: "You are healed by pure water",
    maxRank: 1,
  },
  {
    id: "valkyrie",
    name: "Valkyrie",
    nameRu: "Валькирия",
    description: "You can carry the fallen",
    maxRank: 1,
  },
  {
    id: "venom",
    name: "Venom",
    nameRu: "Яд",
    description: "Your attacks are venomous",
    maxRank: 1,
  },
  {
    id: "veteran",
    name: "Veteran",
    nameRu: "Ветеран",
    description: "You have seen many battles",
    maxRank: 1,
  },
  {
    id: "virulent",
    name: "Virulent",
    nameRu: "Вирулентный",
    description: "Your diseases spread quickly",
    maxRank: 1,
  },
  {
    id: "visage-of-the-runes",
    name: "Visage of the Runes",
    nameRu: "Лик рун",
    description: "Your face is covered in runes",
    maxRank: 1,
  },
  {
    id: "volunteer",
    name: "Volunteer",
    nameRu: "Доброволец",
    description: "You are willing to help",
    maxRank: 1,
  },
  {
    id: "vtree-child",
    name: "VTree Child",
    nameRu: "Древесное дитя",
    description: "You are connected to trees",
    maxRank: 1,
  },
  {
    id: "war-dog",
    name: "War Dog",
    nameRu: "Боевой пёс",
    description: "You have a war dog",
    maxRank: 1,
  },
  {
    id: "warrior-born",
    name: "Warrior Born",
    nameRu: "Воин",
    description: "You are a natural fighter",
    maxRank: 1,
  },
  {
    id: "warrior-lore",
    name: "Warrior Lore",
    nameRu: "Военное знание",
    description: "You know combat techniques",
    maxRank: 1,
  },
  {
    id: "watchman",
    name: "Watchman",
    nameRu: "Сторож",
    description: "You are always alert",
    maxRank: 1,
  },
  {
    id: "water-born",
    name: "Water Born",
    nameRu: "Водяной",
    description: "You can breathe underwater",
    maxRank: 1,
  },
  {
    id: "wealthy",
    name: "Wealthy",
    nameRu: "Богатый",
    description: "You start with more money",
    maxRank: 1,
  },
  {
    id: "whisperer",
    name: "Whisperer",
    nameRu: "Шёптун",
    description: "You can speak to animals",
    maxRank: 1,
  },
  {
    id: "white-lie",
    name: "White Lie",
    nameRu: "Невинная ложь",
    description: "You can lie believably",
    maxRank: 1,
  },
  {
    id: "wight",
    name: "Wight",
    nameRu: "Уэйт",
    description: "You are undead",
    maxRank: 1,
  },
  {
    id: "wild-blood",
    name: "Wild Blood",
    nameRu: "Дикая кровь",
    description: "You have beastman blood",
    maxRank: 1,
  },
  {
    id: "witch",
    name: "Witch",
    nameRu: "Ведьма",
    description: "You can cast witch magic",
    maxRank: 1,
  },
  {
    id: "wizard-blood",
    name: "Wizard Blood",
    nameRu: "Кровь мага",
    description: "You have magical blood",
    maxRank: 1,
  },
  {
    id: "wraith",
    name: "Wraith",
    nameRu: "Призрак",
    description: "You are incorporeal",
    maxRank: 1,
  },
  {
    id: "wrestler",
    name: "Wrestler",
    nameRu: "Борец",
    description: "You can wrestle opponents",
    maxRank: 1,
  },
  {
    id: "zealot",
    name: "Zealot",
    nameRu: "Фанатик",
    description: "You are a religious zealot",
    maxRank: 1,
  },
];

export const getTalentById = (id: string): Talent | undefined =>
  TALENTS.find((t) => t.id === id);
